# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('b', 'Backlog'), ('r', 'Ready'), ('p', 'In Progress'), ('c', 'Complete')], default='h', max_length=1)),
                ('priority', models.CharField(choices=[('h', 'High'), ('m', 'Moderate'), ('l', 'Low')], default='r', max_length=1)),
                ('description', models.TextField(max_length=1250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('status', 'priority', 'created'),
            },
        ),
    ]
